# Generated by Django 6.0.2 on 2026-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('s3_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('local_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('forwarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
